In [25]:
import pandas as pd
import gzip

def parse(path):
  g = gzip.open(path, 'rb')
  for l in g:
    yield eval(l)

def getDF(path):
  i = 0
  df = {}
  for d in parse(path):
    df[i] = d
    i += 1
  return pd.DataFrame.from_dict(df, orient='index')

df = getDF('data/reviews_Patio_Lawn_and_Garden_5.json.gz')

In [ ]:
import numpy as np
df_price = df[np.isfinite(df['price'])]
len(df_price)

In [2]:
test = df.imUrl[1702:16000]
test = test.tolist()

In [ ]:
import urllib
for i, im in enumerate(test):
    try:
        urllib.urlretrieve(im, "data/amazon/images/%i.jpg"%(i+1701))
    except:
        print(i)

2293
3314
4509
4715
4791
5211
6656
7653
7812
9577
9966
10719
10868
11757


In [15]:
from PIL import Image
import numpy as np
import os
dir = "data/amazon/images"
im_list = []
for i in range(8000):
    try:
        im = Image.open(os.path.join(dir, str(i)+".jpg"))
        im = im.resize((32, 32), Image.ANTIALIAS)
        im = np.asarray(im).astype(np.uint8)
        im = im.flatten()
        im_list.append(im.tolist())
    except:
        im = np.zeros(3072).astype(np.uint8)
        im_list.append(im.tolist())
        
    if i%1000 == 0:
        print(i)

im_list = np.array(im_list).astype(np.uint8)
im_list = im_list.flatten()
im_list.tofile("data/amazon/images_1.bin")

    

0
1000
2000
3000
4000
5000
6000
7000


IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



ValueError: setting an array element with a sequence.

In [3]:
import numpy as np
ims = np.fromfile("data/amazon/images.bin", dtype=np.uint8)
len(ims)

196608000

In [12]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [3]:
df.head()

description        asin  \
0  This is real vanilla extract made with only 3 ...  0657745316   
1  Silverpot Tea, Pure Darjeeling, is an exquisit...  0700026444   
2  Must have for any WWE Fan\n \n \n \nFeaturing ...  1403796890   
3  Infused with Vitamins and Electrolytes Good So...  141278509X   
4  MiO Energy is your portable energy source givi...  1453060375   

                                               title  \
0            100 Percent All Natural Vanilla Extract   
1                    Pure Darjeeling Tea: Loose Leaf   
2  WWE Kids Todler Velvet Slippers featuring John...   
3  Archer Farms Strawberry Dragonfruit Drink Mix ...   
4  Mio Energy Liquid Water Enhancer Black Cherry ...   

                   categories  \
0  [[Grocery & Gourmet Food]]   
1  [[Grocery & Gourmet Food]]   
2  [[Grocery & Gourmet Food]]   
3  [[Grocery & Gourmet Food]]   
4  [[Grocery & Gourmet Food]]   

                                               imUrl  \
0  http://ecx.images-amazon.com/images/I/41gFi5h0...   
1  http://ecx.images-amazon.com/images/I/51hs8sox...   
2  http://ecx.images-amazon.com/images/I/518SEST5...   
3  http://ecx.images-amazon.com/images/I/51CFQIis...   
4  http://ecx.images-amazon.com/images/I/51EUsMcn...   

                                             related  \
0                    {'also_viewed': ['B001GE8N4Y']}   
1                                                NaN   
2                                                NaN   
3                    {'also_viewed': ['B0051IETTY']}   
4  {'also_viewed': ['B006MSEOJ2', 'B005VOOQLO', '...   

                            salesRank  price brand  
0  {'Grocery & Gourmet Food': 374004}    NaN   NaN  
1  {'Grocery & Gourmet Food': 620307}    NaN   NaN  
2                                 NaN   3.99   NaN  
3  {'Grocery & Gourmet Food': 620322}    NaN   NaN  
4  {'Grocery & Gourmet Food': 268754}  11.99   Mio

In [157]:
movies = list(open("data/ml-1m/movies.dat", "r").readlines())
movies = [m.strip() for m in movies]
movies[:10]

["1::Toy Story (1995)::Animation|Children's|Comedy",
 "2::Jumanji (1995)::Adventure|Children's|Fantasy",
 '3::Grumpier Old Men (1995)::Comedy|Romance',
 '4::Waiting to Exhale (1995)::Comedy|Drama',
 '5::Father of the Bride Part II (1995)::Comedy',
 '6::Heat (1995)::Action|Crime|Thriller',
 '7::Sabrina (1995)::Comedy|Romance',
 "8::Tom and Huck (1995)::Adventure|Children's",
 '9::Sudden Death (1995)::Action',
 '10::GoldenEye (1995)::Action|Adventure|Thriller']

In [2]:
ratings = list(open("data/ml-1m/ratings.dat", "r").readlines())
ratings = [r.strip() for r in ratings]
ratings[:10]

['1::1193::5::978300760',
 '1::661::3::978302109',
 '1::914::3::978301968',
 '1::3408::4::978300275',
 '1::2355::5::978824291',
 '1::1197::3::978302268',
 '1::1287::5::978302039',
 '1::2804::5::978300719',
 '1::594::4::978302268',
 '1::919::4::978301368']

In [4]:
import numpy as np
links = list(open("data/ml-1m/links.csv", "r").readlines())
links = [l.strip() for l in links]
links = [l.split(",") for l in links]
links = np.array(links)
links[:5]


array([['movieId', 'imdbId', 'tmdbId'],
       ['1', '0114709', '862'],
       ['2', '0113497', '8844'],
       ['3', '0113228', '15602'],
       ['4', '0114885', '31357']],
      dtype='|S7')

In [142]:
movie_description = list(open("data/ml-1m/movie_description.txt", "r").readlines())
movie_description = [m.strip() for m in movie_description]
link_des = []
movie_des = []
for i, m in enumerate(movie_description):
    if i%2 == 0:
        link_des.append(m)
    else:
        movie_des.append(m)

In [143]:
for i, m in enumerate(movies):
    idx = m.split("::")[0]
    link_id = np.where(links[:,0] == idx)
    if len(link_id[0]) == 0:
        print(i, m)
    else:
        link_id = link_id[0][0]
        if links[link_id,1] not in link_des[i]:
            print(m, links[link_id])
            break

(553, '557::Mamma Roma (1962)::Drama')
(574, '578::Hour of the Pig, The (1993)::Drama|Mystery')
(663, '669::Aparajito (1956)::Drama')
(801, '811::Bewegte Mann, Der (1994)::Comedy')
(852, '863::Celestial Clockwork (1994)::Comedy')
(966, '978::Blue Angel, The (Blaue Engel, Der) (1930)::Drama')
(1092, '1108::Prerokbe Ognja (1995)::Documentary')
(1187, "1205::Transformers: The Movie, The (1986)::Action|Animation|Children's|Sci-Fi|Thriller|War")
(1274, '1294::M*A*S*H (1970)::Comedy|War')
(1341, '1362::Garden of Finzi-Contini, The (Giardino dei Finzi-Contini, Il) (1970)::Drama')
(1462, '1494::Sixth Man, The (1997)::Comedy')
(1690, '1741::Midaq Alley (Callej\xf3n de los milagros, El) (1995)::Drama')
(1705, '1758::Dangerous Beauty (1998)::Drama')
(1799, '1868::Truce, The (1996)::Drama|War')
(2159, '2228::Mountain Eagle, The (1926)::Drama')
(2576, '2645::Dracula (1958)::Horror')
(2958, '3027::Slaughterhouse 2 (1988)::Horror')
(3297, '3366::Where Eagles Dare (1969)::Action|Adventure|War')
(3347,

In [145]:
ratings = [r.split("::") for r in ratings]
ratings = np.array(ratings)
len(np.unique(ratings[:,0]))

6040

In [158]:
movies = [m.split("::") for m in movies]
movies = np.array(movies)
len(np.unique(movies[:,0]))

3883

In [161]:
text = [(movies[i,1] +' '+ movie_des[i]) for i in range(len(movies)) ]
text = np.array(text)
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english', max_features=8000)
X_train = tfidf.fit_transform(text)
from scipy.sparse import save_npz
save_npz("data/ml-1m/mult_nor.npz", X_train)

In [189]:
import urllib2
from bs4 import BeautifulSoup
character = []
for i in range(2585, len(link_des)):
    link = link_des[i]
    link = link.split("plotsummary")[0] + '?ref_=nv_sr_1'
    page = urllib2.urlopen(link).read()
    soup = BeautifulSoup(page)
    soup.prettify()
    try:
        soup = soup.find("table", {'class':"cast_list"})
        soup = soup.find_all("span", {'itemprop':"name"})
        c = []
        for s in soup:
            c.append(s.text)
        character.append(c)
        if i%100 == 0:
            print(i)
    except:
        character.append([])
        print(i)

2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3608
3700
3800


In [207]:
movies[1,2]

"Adventure|Children's|Fantasy"

In [198]:
c2 = []
for c in characters:
    for j, i in enumerate(c):
        if i not in c2:
            c2.append(i)
        if j == 4:
            break

In [237]:
len(c2)

9945

In [280]:
user = [0]*6040
user_sort = [0] *6040
import math

for i, r in enumerate(ratings):
    movieid = movie_ids.index(r[1])
    movie_type = movies[movieid, 2].split("|")
    day = (math.ceil(r[3]/8640)%7 +3)%7
    if user[r[0]-1] == 0:
        user[r[0]-1] = [movieid, r[2], r[3], day, movie_type, characters[movieid]]
        user_sort[r[0]-1] = [movieid, r[3]]
    else:
        user[r[0]-1].append([movieid, r[2], r[3], day, movie_type, characters[movieid]])
        user_sort[r[0]-1].append([movieid, r[3]])
    if i%1000 == 0:
        print(i)
        

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000
130000
131000
132000
133000
134000
135000
136000
137000
138000
139000
140000
141000
142000
143000
144000
145000
146000
147000
148000
149000
150000
151000
152000
153000
154000
155000
156000
157000
158000


In [229]:
x = user_sort[1]
n = x[:2]
x = x[2:]
x.insert(0,n)
x = np.array(x)
x = x[x[:,1].argsort()]

In [230]:
user_rating = [0]*6040

for i in range(6040):
    x = user_sort[i]
    n = x[:2]
    x = x[2:]
    x.insert(0, n)
    x = np.array(x)
    x = x[x[:,1].argsort()]
    user_rating[i] = list(x[:, 0])

In [234]:
f = open("data/ml-1m/user_ratings.txt", "w")
for u in user_rating:
    f.write("%d"%len(u))
    for i in u:
        f.write(" %d"%i)
    f.write("\n")

In [287]:
for i in range(6040):
    x = user[i]
    n = x[:6]
    x = x[6:]
    x.insert(0, n)
    user[i] = x

In [240]:
train_user = open("data/ml-1m/cf-train-70p-users.dat", "w")
test_user = open("data/ml-1m/cf-test-70p-users.dat", "w")
train_item = open("data/ml-1m/cf-train-70p-items.dat", "w")
test_item = open("data/ml-1m/cf-test-70p-items.dat", "w")
item_train = [0]*3883
item_test = [0]*3883

for i, r in enumerate(user_rating):
    train_num = int(len(r)*0.7)
    train_user.write("%d"%(train_num))
    test_user.write(" %d"%(len(r[train_num:])))
    for j in r[:train_num]:
        train_user.write(" %d"%j)
        if item_train[j] == 0:
            item_train[j] = [i]
        else:
            item_train[j].append(i)
    train_user.write("\n")
    for j in r[train_num:]:
        test_user.write(" %d"%j)
        if item_test[j] == 0: 
            item_test[j] = [i]
        else:
            item_test[j].append(i)
    test_user.write("\n")
            
for i in item_train:
    if i == 0:
        train_item.write("0\n")
    else:
        train_item.write("%d"%len(i))
        for j in i:
            train_item.write(" %d"%j)
        train_item.write("\n")
    
for i in item_test:
    if i == 0:
        test_item.write("0\n")
    else:
        test_item.write("%d"%len(i))
        for j in i:
            test_item.write(" %d"%j)
        test_item.write("\n")
    
train_user.close()
test_user.close()
train_item.close()
test_item.close()

In [397]:
train = list(open("data/ml-1m/cf-train-5-users.dat", "r").readlines())
train = [t.strip() for t in train]
train = [t.split(" ") for t in train]
train = [t[1:] for t in train]
train = [[int(i) for i in t] for t in train]

In [289]:
movie_type = []
for m in movies:
    t = m[2].split("|")
    for i in t:
        if i not in movie_type:
            movie_type.append(i)

In [398]:
user_info = np.zeros((6040, 9975))
for i, u in enumerate(user):
    for info in u:
        j = 0
        if info[0] in train[i]:
            day = ((int(info[2]/(24*60*60)) + 1)%7 + 3)%7
            user_info[i, day] += 1
            rating = int(info[1])
            
            user_info[i, rating + 6] += 1
            for t in info[4]:
                idx = movie_type.index(t)
                user_info[i, 12+idx] += 1
            for k, c in enumerate(info[5]):
                if k < 5:
                    idx = c2.index(c)
                    user_info[i, 30+idx] += 1
            j += 1
    day_count = sum(user_info[i, :7])
    rating_count = sum(user_info[i, 7:12])
    type_count = sum(user_info[i, 12:30])
    character_count = sum(user_info[i, 30:])

    for j in range(7):
        user_info[i,j] = float(user_info[i,j])/day_count
    for j in range(7, 12):
        user_info[i,j] = float(user_info[i,j])/rating_count
    for j in range(12, 30):
        user_info[i,j] = float(user_info[i,j])/type_count
    for j in range(30, 9975):
        user_info[i,j] = float(user_info[i,j])/character_count

In [399]:
user_info = np.array(user_info)
np.save("data/ml-1m/user_info_52.npy", user_info)

In [259]:
((int(978824268/(24*60*60))+1)%7 + 3)%7

6

In [333]:
np.argwhere(np.isnan(user_info))


array([], shape=(0, 2), dtype=int64)

In [305]:
import datetime
user_ids = list(open("data/TV/user_ids.txt", "r").readlines())
user_ids = [u.strip() for u in user_ids]
user = [0] * len(user_ids)

product_ids = list(open("data/TV/product_ids.txt", "r").readlines())
product_ids = [p.strip() for p in product_ids]

f = open("data/TV/review_info.txt", "w")
user_rate_info = []
user_rate_info.append(["u_id", "p_id", "rating", "unixTime", "categories"])
f.write("u_id, p_id, rating, unixTime, categories")
i = 0
for index, r in rating.iterrows():
    try:
        u_id = user_ids.index(r.reviewerID)
        p_id = product_ids.index(r.asin)
        if user[u_id] == 0:
            user[u_id] = [p_id]
        else:
            user[u_id].append(p_id)
        product = products.loc[products['asin'] == r.asin]
        categories = list(product.categories)
        categories = product.categories[0]
        brand = list(product.brand)[0]
        print(brand)
        user_rate_info.append([u_id, p_id, r.overall, r.unixTime, categories, brand])
        f.write("%d, %d, %d, %s, %s, %s"%(u_id, p_id, r.overall, r.unixTime, categories, brand))
        i+= 1
    except:
        None

    if i %1000 == 100:
        print(index, i)
        break

f.close()


[[3211,
  5,
  977979487,
  5.0,
  ['Horror'],
  [u'Anjanette Comer',
   u'Ruth Roman',
   u'Marianna Hill',
   u'Susanne Zenor',
   u'Tod Andrews',
   u'Michael Pataki',
   u'Beatrice Manley',
   u"Erin O'Reilly",
   u'Don Mallon',
   u'Joseph Bernard',
   u'Virginia Vincent',
   u'David Mooney']],
 [2559,
  1,
  977979482,
  5.0,
  ['Action', 'Adventure', 'Fantasy', 'Sci-Fi'],
  [u'Liam Neeson',
   u'Ewan McGregor',
   u'Natalie Portman',
   u'Jake Lloyd',
   u'Ian McDiarmid',
   u'Pernilla August',
   u'Oliver Ford Davies',
   u'Hugh Quarshie',
   u'Ahmed Best',
   u'Anthony Daniels',
   u'Kenny Baker',
   u'Frank Oz',
   u'Terence Stamp',
   u'Brian Blessed',
   u'Andy Secombe']],
 [3869,
  5,
  977979062,
  5.0,
  ['Horror'],
  [u'Crystal Bernard',
   u'Jennifer Rhodes',
   u'Kimberly McArthur',
   u'Patrick Lowe',
   u'Juliette Cummins',
   u'Heidi Kozak',
   u'Cindy Eilbacher',
   u'Atanas Ilitch',
   u'Joel Hoffman',
   u'Scott Westmoreland',
   u'Michael DeLano',
   u'Hamilton

In [258]:
11329%7

3

In [279]:
f = open("data/ml-1m/characters.text", "w")
import string
printable = set(string.printable)
for c in characters:
    s = ','.join(c)
    s = filter(lambda x: x in printable, s)
    f.write("%s\n"%s)

In [286]:
u[1]

5

In [292]:
(0.0519-0.0518)/0.0518

0.0019305019305019858

In [323]:
user2 = np.zeros((6040, 3883))

for i in range(6040):
    for j in train[i]:
        user2[i,j] = 1

In [345]:
train_vec = []
for i, u in enumerate(user):
    for info in u:
        j = 0
        if info[0] in train[i]:
            train_vec.append([i, info[0], info[1]])
        

In [346]:
len(train_vec)

90600

In [348]:
f = open("data/ml-1m/train-15.csv", "w")
f.write("userID, productID, rating\n")
for i in train_vec[89000:]:
    f.write("%d, %d, %d\n"%(i[0], i[1], i[2]))
f.close()

In [355]:
data = list(open("data/train.csv").readlines())
data = data[1:]
data = [d.strip() for d in data]
data = [d.split(",") for d in data]
data = [d[1:] for d in data]
data = np.array(data).astype(np.float32)

In [372]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
X_train, X_test, y_train, y_test = train_test_split(data[:, 1:], data[:, 0], test_size=0.3, random_state=0)

In [373]:
lm = DecisionTreeRegressor()
lm.fit(X_train, y_train)
pred = lm.predict(X_test)
RMSLE(pred, y_test)

/Users/linh/PhD/code/.env/lib/python2.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
/Users/linh/PhD/code/.env/lib/python2.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in subtract
  


nan

In [363]:
def RMSLE(pred, label):
    return np.sqrt(np.mean(np.square( np.log( (np.exp(pred)) + 1 ) - np.log((np.exp(label))+1) )))


In [368]:
y_test[:3]

array([ 32000000.,    400000.,  10000000.], dtype=float32)

In [377]:
np.argwhere(np.isnan(np.exp(pred)))


/Users/linh/PhD/code/.env/lib/python2.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in exp
  """Entry point for launching an IPython kernel.


array([], shape=(0, 1), dtype=int64)

In [380]:
pred[:3]

array([  9100000.,    511000.,  20000000.])

In [382]:
y_test[:3]

array([ 32000000.,    400000.,  10000000.], dtype=float32)

In [402]:
user_info = np.zeros((5584, 742))
rating = np.zeros(5584)
import datetime
for r in user_rate_info:
    if int(r[1]) in train[r[0]]:
        user_info[r[0]][r[2]] +=1
        t = int(r[3]) +6
        user_info[r[0]][t] += 1
        if r[0] == 0:
            print(r[1])
        for c in r[4]:
            i = categories.index(c)
            user_info[r[0]][i+12] += 1

0.002117135323440518

In [403]:
1294185600
import datetime
print(
    datetime.datetime.fromtimestamp(
        int("1294185600")
    ).strftime('%Y-%m-%d %H:%M:%S')
)

2011-01-05 09:00:00


In [426]:
data = list(open("data/sport/train-8.csv").readlines())[1:]
data = data + list(open("data/ml-1m/val-8.csv").readlines())[1:]
data = [d.strip() for d in data]
data = [d.split(",") for d in data]
data = np.array(data).astype(np.int32)

train = list(open("data/sport/cf-train-8-users.dat").readlines())
train = [t.strip() for t in train]
train = [t.split(" ") for t in train]
no_item = [int(t[0]) for t in train]
train = [t[1:] for t in train]

user = [[0]*i for i in no_item]

train_item = list(open("data/sport/cf-train-8-items.dat").readlines())
train_item = [t.strip() for t in train_item]
train_item = [t.split(" ") for t in train_item]
no_user = [int(t[0]) for t in train_item]
train_item = [t[1:] for t in train_item]

item = [[0]*i for i in no_user]

In [427]:
train = [[int(i) for i in t] for t in train]
train_item = [[int(j) for j in m] for m in train_item]
for d in data:
    if d[1] in train[d[0]]:
        itemID = train[d[0]].index(d[1])
        user[d[0]][itemID] = d[2]

        userID = train_item[d[1]].index(d[0])
        item[d[1]][userID] = d[2]


In [432]:
np.tile(user[1], (50, 1)).T

array([[4, 4, 4, ..., 4, 4, 4],
       [3, 3, 3, ..., 3, 3, 3],
       [4, 4, 4, ..., 4, 4, 4],
       ..., 
       [4, 4, 4, ..., 4, 4, 4],
       [4, 4, 4, ..., 4, 4, 4],
       [5, 5, 5, ..., 5, 5, 5]], dtype=int32)

In [ ]:
from urllib2 import urlopen
import os
files = ['Clothing_Shoes_and_Jewelry', 'Sports_and_Outdoors', 'Toys_and_Games', 'Video_Games', 'Tools_and_Home_Improvement', 'Beauty', 'Office_Products', 'Baby']
folders = ['Clothing', 'Outdoor', 'Toy', 'Video', 'Tool', 'Beauty', 'Office', 'Baby']
for i, f in enumerate(files):
    try:
        os.makedirs("data/%s/"%folders[i])
        url = 'http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/reviews_%s_5.json.gz'%f
        data = urlopen(url)
        with open("data/%s/reviews.json.gz"%folders[i], "wb") as local_file:
            local_file.write(data.read())
        data.close()
        local_file.close()
        print("Finish review %s"%folders[i])
        
        url = 'http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/meta_%s.json.gz'%f
        data = urlopen(url)
        with open("data/%s/meta.json.gz"%folders[i], "wb") as local_file:
            local_file.write(data.read())
        data.close()
        local_file.close()
        print("Finish meta %s"%folders[i])
    except:
        print("Fail %s"%folders[i])


In [ ]:
folders = ['Clothing', 'Outdoor', 'Toy', 'Video', 'Tool', 'Beauty', 'Office', 'Baby']
for f in folders:
    rating = getDF("data/%s/reviews.json.gz")
    print("%s \t num_user: %d\t num_item:%d"%(%f, len(np.unique(rating.reviewerID)), len(np.unique(rating.asin))))
    f = pr

In [443]:
import numpy as np
x = np.array(['a', 'a', 'b', 'c', 'c', 'c'])
unique, counts = np.unique(x, return_counts=True)


In [436]:
t = np.vstack((ii,y[ii])).T
t[np.where(t[:,1] >1)]

array([[1, 5],
       [2, 3]])

In [444]:
folders = ['Outdoor', 'Toy', 'Tool', 'Beauty', 'Electronics', 'TV']
for fo in folders:
    user_ids = list(open("data/%s/user_ids.txt"%fo, "r").readlines())
    user_ids = [u.strip() for u in user_ids]
    user = [0] * len(user_ids)

    product_ids = list(open("data/%s/product_ids.txt"%fo, "r").readlines())
    product_ids = [p.strip() for p in product_ids]

    f = open("data/%s/review_info.txt"%fo, "w")
    user_rate_info = []
    user_rate_info.append(["u_id", "p_id", "rating", "unixTime", "categories"])
    f.write("u_id, p_id, rating, unixTime, categories")
    i = 0
    for index, r in rating.iterrows():
        try:
            u_id = user_ids.index(r.reviewerID)
            p_id = product_ids.index(r.asin)
            if user[u_id] == 0:
                user[u_id] = [p_id]
            else:
                user[u_id].append(p_id)
            product = products.loc[products['asin'] == r.asin]
            categories = list(product.categories)
            categories = categories[0][0]
            brand = list(product.brand)[0]
            user_rate_info.append([u_id, p_id, r.overall, r.unixTime,brand, categories])
            f.write("%d, %d, %d, %s, %s"%(u_id, p_id, r.overall, r.unixTime, brand))
            for c in categories:
                f.write(",%s"%c)
            f.write("\n")
            i+= 1
        except:
            None

        if index %1000 == 500:
            print(index, i)
    f.close()
    f = open("data/%s/user_product.txt"%fo, "w")
    for u in user:
        f.write("%d"%len(u))
        for i in u:
            f.write(" %d"%i)
        f.write("\n")
    f.close()


array(['a', 'c'],
      dtype='|S1')

In [ ]:
product = getDF("data/Baby/meta.json.gz")
product = product[pd.notnull(product.description)]
product = product[pd.notnull(product.imUrl)]
product = product[pd.notnull(product.categories)]
product = product[pd.notnull(product.brand)]
print(len(np.unique(product.asin)))
product_id = list(set(rating.asin) & set(product.asin))

In [1]:
l = [3,5,6]
for i, r in enumerate(l):
    print(i,r)

(0, 3)
(1, 5)
(2, 6)


In [2]:
from scipy.sparse import load_npz
variables = load_npz("Health_Clothing/mult_nor.npz")
data = variables.toarray()

In [9]:
import numpy as np
d = np.matmul(data,data.T)
norm = (data * data).sum(1, keepdims=True) ** .5

In [11]:
norm = (data * data).sum(1, keepdims=True) ** .5
print(norm.shape)
d.shape

(34295, 1)


(34295, 34295)

In [12]:
cosin = d/norm/norm.T

In [13]:
cosin.shape

(34295, 34295)

In [21]:
m = 0
max_i = 0
max_j = 0
for i in range(16069):
    for j in range(16069, 34295):
        if cosin[i,j] > m and cosin[i,j] < 0.9:
            m = cosin[i,j]
            max_i = i
            max_j = j
m

0.89667810771109302

In [17]:
np.save("Health_Clothing/sim.npy", cosin)

In [22]:
max_i

3236

In [23]:
max_j

17875

In [1]:
def read_data(f, s=",", int_or_not=True):
    predict = list(open(f, "r"))
    predict = [p.strip() for p in predict]
    if s!="":
        predict = [p.split(s) for p in predict]
    if int_or_not:
        predict = [[int(i) for i in p] for p in predict]
    return predict

In [93]:
comedy_id = read_data("Health_Clothing/Comedy_ids.txt", "",False)
comedy_id = [int(d) for d in comedy_id]
comedy = read_data("Health_Clothing/Comedy_user_product.txt", " ")
drama_id = read_data("Health_Clothing/Drama_ids.txt", "",False)
drama_id = [int(d) for d in drama_id]
drama = read_data("Health_Clothing/Drama_user_product.txt", " ")
movies = read_data("Health_Clothing/ml-1m/movies.dat", "::", False)

[14, 0, 260, 727, 689, 194, 770, 157, 297, 695, 561, 570, 1012, 314, 384]

In [51]:
train_size = int(len(comedy)*0.7)
test_size = int(len(comedy)*0.75)

In [176]:
for i in drama[check[4]]:
    for m in movies:
        if int(m[0]) == drama_id[i]:
            print(m)

['40', 'Cry, the Beloved Country (1995)', 'Drama']
['32', 'Twelve Monkeys (1995)', 'Drama|Sci-Fi']
['2672', 'Thirteenth Floor, The (1999)', 'Drama|Sci-Fi|Thriller']
['1097', 'E.T. the Extra-Terrestrial (1982)', "Children's|Drama|Fantasy|Sci-Fi"]
['1196', 'Star Wars: Episode V - The Empire Strikes Back (1980)', 'Action|Adventure|Drama|Sci-Fi|War']
['3471', 'Close Encounters of the Third Kind (1977)', 'Drama|Sci-Fi']
['1584', 'Contact (1997)', 'Drama|Sci-Fi']
['3699', 'Starman (1984)', 'Adventure|Drama|Romance|Sci-Fi']
['1396', 'Sneakers (1992)', 'Crime|Drama|Sci-Fi']
['1653', 'Gattaca (1997)', 'Drama|Sci-Fi|Thriller']
['3510', 'Frequency (2000)', 'Drama|Thriller']
['1721', 'Titanic (1997)', 'Drama|Romance']
['3578', 'Gladiator (2000)', 'Action|Drama']
['3571', 'Time Code (2000)', 'Drama']


In [121]:
for i in comedy[3362]:
    for m in movies:
        if int(m[0]) == comedy_id[i]:
            print(m)

['7', 'Sabrina (1995)', 'Comedy|Romance']
['2699', 'Arachnophobia (1990)', 'Action|Comedy|Sci-Fi|Thriller']
['1580', 'Men in Black (1997)', 'Action|Adventure|Comedy|Sci-Fi']
['1215', 'Army of Darkness (1993)', 'Action|Adventure|Comedy|Horror|Sci-Fi']


In [140]:
stat = []
for i in range(len(comedy)):
    l = [0]*19
    l[0] = len(comedy[i])
    for j in comedy[i]:
        for m in movies:
            if int(m[0]) == comedy_id[j]:
                s = m[2].split("|")
                for k in s:
                    l[genres.index(k)+1] += 1
    
    stat.append(l)


In [70]:
import numpy as np
stat = np.zeros((len(a), 3))
for i in range(len(a)):
    stat[i, 0] = len(drama[a[i]])
    for j in drama[a[i]]:
        for m in movies:
            if int(m[0]) == j:
                if 'Action' in m[2]:
                    stat[i, 1] += 1
                if 'Sci-Fi' in m[2]:
                    stat[i, 2] += 1
    

In [172]:
drama_stat = []
for i in check:
    l = [0]*19
    l[0] = len(drama[i])
    for j in drama[i]:
        for m in movies:
            if int(m[0]) == drama_id[j]:
                s = m[2].split("|")
                for k in s:
                    l[genres.index(k)+1] += 1
    
    drama_stat.append(l)

In [186]:
num = 0
for i, d in enumerate(drama_stat):
    if i in v:
        print(d)
        if d[3] < d[13]:
            print("---")

[14, 0, 14, 9, 1, 0, 0, 1, 2, 1, 0, 0, 2, 2, 0, 0, 1, 3, 0]
[16, 1, 16, 14, 1, 0, 0, 2, 2, 1, 0, 0, 2, 3, 0, 0, 2, 4, 0]
[31, 1, 31, 11, 1, 0, 0, 4, 1, 1, 0, 0, 4, 20, 3, 0, 6, 7, 0]
---
[20, 1, 20, 13, 1, 0, 0, 2, 2, 1, 0, 0, 2, 4, 0, 0, 2, 8, 0]
[14, 1, 14, 11, 1, 0, 0, 2, 1, 1, 0, 0, 1, 0, 0, 0, 1, 2, 0]
[27, 1, 27, 13, 0, 0, 0, 2, 2, 0, 0, 0, 3, 8, 0, 0, 7, 5, 0]
[37, 5, 37, 10, 1, 0, 2, 9, 3, 1, 0, 0, 1, 6, 1, 0, 6, 12, 0]
[23, 1, 23, 12, 1, 0, 0, 5, 1, 1, 0, 0, 2, 11, 0, 0, 4, 3, 0]
[13, 0, 13, 11, 1, 0, 0, 1, 1, 1, 0, 0, 2, 3, 0, 0, 1, 3, 0]
[19, 1, 19, 11, 1, 0, 0, 3, 2, 1, 0, 0, 2, 8, 0, 0, 6, 3, 0]
[71, 2, 71, 14, 2, 0, 0, 10, 8, 1, 0, 0, 9, 47, 2, 0, 10, 11, 6]
---
[13, 0, 13, 9, 1, 0, 0, 3, 1, 1, 0, 0, 2, 1, 0, 0, 1, 2, 0]
[11, 1, 11, 9, 0, 0, 0, 1, 1, 0, 0, 0, 3, 2, 0, 0, 1, 2, 0]
[43, 2, 43, 11, 2, 0, 0, 9, 3, 1, 0, 0, 5, 31, 4, 0, 7, 4, 0]
---
[35, 1, 35, 12, 1, 0, 0, 9, 3, 2, 1, 0, 5, 21, 3, 0, 4, 6, 0]
---


In [189]:
v = []
for i, c in enumerate(check):
    if len(set(comedy[c]) & set(comedy[test_size+1463])) > 5:
        print(stat[c])
        v.append(i)

[18  0  0 14  1  1  0  1  0  3  0  0  4  3 18  0  1  0  1]
[19  0  0 18  1  3  0  0  3  1  1  0  4  4 19  0  1  1  0]
[36  0  0 16  1  4  0  3  5  2  4  1 13 21 36  0  2  3  3]
[17  0  0 15  2  1  0  0  2  2  2  0  4  4 17  0  1  1  1]
[12  0  0  9  0  2  0  0  1  0  1  0  4  3 12  0  0  1  0]
[17  0  0 13  1  2  0  1  2  2  1  0  7  5 17  0  0  1  1]
[16  2  1  9  0  1  0  3  2  0  0  0  4  5 16  0  0  4  0]
[15  0  1 11  1  0  0  0  0  1  0  0  4  3 15  0  0  1  1]
[21  0  0 17  2  1  0  1  1  1  2  0  3  4 21  0  1  1  1]
[18  0  2 13  2  2  0  0  2  1  2  0  5  5 18  0  1  0  0]
[43  0  1 15  1  0  0  2  4  2  3  0 13 22 43  0  3  2  9]
[23  0  1 17  2  1  0  0  1  3  2  1  6  5 23  0  1  1  2]
[13  0  0  9  0  0  0  0  0  1  0  0  3  2 13  0  0  0  1]
[44  0  0 16  3  2  0  2  4  3  4  1 10 28 44  0  3  1  4]
[33  0  1 13  0  1  0  3  6  1  2  1 13 18 33  0  2  2  1]


In [169]:
check = []
for i, s in enumerate(stat):
    l = np.argsort(s)[-5:]
    if i > test_size:
        break
    if len(set(l) & set([0, 3, 12, 13, 14])) == 5 and float((s[3]+s[12]+s[13]))/s[14] > 1.0 and s[14]>10:
        check.append(i)

In [152]:
stat[test_size+1463]

[11, 0, 0, 8, 0, 1, 0, 0, 0, 0, 0, 0, 4, 3, 11, 0, 0, 0, 0]

In [170]:
stat[]

43

In [130]:
l = [1,3,4,5,2]
if np.sort(l) == np.array([1,2,3,4,5]):
    print("a")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [3]:
data = df
data.head()

reviewerID        asin                            reviewerName helpful  \
0  A1JZFGZEZVWQPY  B00002N674  Carter H "1amazonreviewer@gmail . com"  [4, 4]   
1  A32JCI4AK2JTTG  B00002N674               Darryl Bennett "Fuzzy342"  [0, 0]   
2  A3N0P5AAMP6XD2  B00002N674                                     H B  [2, 3]   
3   A2QK7UNJ857YG  B00002N674                                   Jason  [0, 0]   
4   AS0CYBAN6EM06  B00002N674                                   jimmy  [1, 1]   

   unixReviewTime                                         reviewText  overall  \
0      1308614400  Good USA company that stands behind their prod...      4.0   
1      1402272000  This is a high quality 8 ply hose. I have had ...      5.0   
2      1336176000  It's probably one of the best hoses I've ever ...      4.0   
3      1373846400  I probably should have bought something a bit ...      5.0   
4      1375660800  I bought three of these 5/8-inch Flexogen hose...      5.0   

    reviewTime                                            summary  
0  06 21, 2011                                        Great Hoses  
1   06 9, 2014  Gilmour 10-58050 8-ply Flexogen Hose 5/8-Inch ...  
2   05 5, 2012                                    Very satisfied!  
3  07 15, 2013                                  Very high quality  
4   08 5, 2013                                         Good Hoses

In [5]:
import gensim
from gensim.models import KeyedVectors

model = KeyedVectors.load_word2vec_format('data/GoogleGoogleNews-vectors-negative300.bin', binary=True)
model['dog']

IOError: [Errno 2] No such file or directory: 'data/GoogleGoogleNews-vectors-negative300.bin'

In [23]:
df= df.dropna()
df = df[df.reviewText.apply(lambda x: x !="")]
df['reviewText'] = df['reviewText'].map(lambda x: clean_text(x))

ValueError: translation table must be 256 characters long

13272

In [26]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Flatten, LSTM, Conv1D, MaxPooling1D, Dropout, Activation
from keras.layers.embeddings import Embedding
## Plotly
import plotly.offline as py
import plotly.graph_objs as go
py.init_notebook_mode(connected=True)
# Others
import nltk
import string
import numpy as np
import pandas as pd
from nltk.corpus import stopwords


from sklearn.manifold import TSNE
def clean_text(text):
    
    ## Remove puncuation
    text = text.translate(string.punctuation)

    ## Convert words to lower case and split them
    text = text.lower().split()

    ## Remove stop words
    stops = set(stopwords.words("english"))
    text = [w for w in text if not w in stops and len(w) >= 3]

    text = " ".join(text)
    ## Clean the text
    text = re.sub(r"[^A-Za-z0-9^,!.\/'+-=]", " ", text)
    text = re.sub(r"what's", "what is ", text)
    text = re.sub(r"\'s", " ", text)
    text = re.sub(r"\'ve", " have ", text)
    text = re.sub(r"n't", " not ", text)
    text = re.sub(r"i'm", "i am ", text)
    text = re.sub(r"\'re", " are ", text)
    text = re.sub(r"\'d", " would ", text)
    text = re.sub(r"\'ll", " will ", text)
    text = re.sub(r",", " ", text)
    text = re.sub(r"\.", " ", text)
    text = re.sub(r"!", " ! ", text)
    text = re.sub(r"\/", " ", text)
    text = re.sub(r"\^", " ^ ", text)
    text = re.sub(r"\+", " + ", text)
    text = re.sub(r"\-", " - ", text)
    text = re.sub(r"\=", " = ", text)
    text = re.sub(r"'", " ", text)
    text = re.sub(r"(\d+)(k)", r"\g<1>000", text)
    text = re.sub(r":", " : ", text)
    text = re.sub(r" e g ", " eg ", text)
    text = re.sub(r" b g ", " bg ", text)
    text = re.sub(r" u s ", " american ", text)
    text = re.sub(r"\0s", "0", text)
    text = re.sub(r" 9 11 ", "911", text)
    text = re.sub(r"e - mail", "email", text)
    text = re.sub(r"j k", "jk", text)
    text = re.sub(r"\s{2,}", " ", text)
    ## Stemming
    text = text.split()
    stemmer = SnowballStemmer('english')
    stemmed_words = [stemmer.stem(word) for word in text]
    text = " ".join(stemmed_words)
    return text

In [27]:
text = df['reviewText'][0]
text

'Good USA company that stands behind their products. I have had to warranty two hoses and they send replacements right out to you. I had one burst after awhile, you could see it buldge for weeks before it went so no suprises. The other one was winter related as I am bad and leave them out most of the time. Highly reccomend. Note the hundred footer is heavy and like wresting an anaconda when its time to put away, but it does have a far reach.'